//! The synthetic process set (§8.1, §12.5): 32 rows shaped like torch under a
//! game — a game at 12.5 GiB VRAM / 17 % SM (its `Both` GPU row arrives with
//! 2b), a shell, a browser with threads, kernel threads, VIRT/RES values in
//! all three `Row_printKBytes` regimes, and one PID that vanishes and
//! reappears. Same seed and tick → byte-identical table.

use std::sync::Arc;

use crate::demo::XorShift;
use crate::keys::cpu::{ProcRow, ProcTable};

/// torch's kernel-thread count (research digest): the synthetic `tasks.kernel`.
pub const KERNEL_THREADS: f64 = 431.0;

/// PID column width the synth claims: `pid_max` 4194304 → 7 digits, as on torch.
pub const PID_DIGITS: u8 = 7;

const MEM_TOTAL_KIB: f64 = 91.0 * 1024.0 * 1024.0;

/// One template row: everything static about a process; the per-tick jitter
/// is applied on top.
struct Template {
    pid: i32,
    ppid: i32,
    uid: u32,
    user: &'static str,
    state: char,
    pri: i16,
    nice: i16,
    nlwp: u32,
    virt_kib: u64,
    res_kib: u64,
    shr_kib: u64,
    /// Mean CPU% (Irix mode, so a threaded process can exceed 100).
    cpu: f32,
    /// TIME+ at tick 0, in centiseconds.
    time_cs: u64,
    starttime: u64,
    kthread: bool,
    cmdline: &'static str,
    comm: &'static str,
    /// Present only on ticks where `(tick / 8) % 2 == 0` — the PID that comes
    /// and goes (tomb rows are arc 8; the data exists now).
    flicker: bool,
    /// Block-layer bytes a second, for htop's I/O screen (arc 8a). Most
    /// processes move none; the backup and the browser do.
    read_bps: f32,
    write_bps: f32,
}

const M: &str = "mattbeam";
const R: &str = "root";

/// The set. Regimes for RES/VIRT: `< 1000` KiB (kworker: 0), `1000–99 999`
/// (bash 28248 → `28248` with `28` in the M role), `≥ 100 000` (`97.6M`,
/// `9.76G`, `12.5G` for the game's host memory, `1000M`+ for firefox's VIRT).
const SET: &[Template] = &[
    Template {
        pid: 412345,
        ppid: 2801,
        uid: 1000,
        user: M,
        state: 'R',
        pri: 20,
        nice: 0,
        nlwp: 63,
        virt_kib: 34_500_000,
        res_kib: 13_107_200,
        shr_kib: 1_540_000,
        cpu: 412.0,
        time_cs: 1_234_567,
        starttime: 1_580_000,
        kthread: false,
        cmdline: "/opt/game/bin/game --fullscreen --vulkan",
        comm: "game",
        flicker: false,
        read_bps: 0.0,
        write_bps: 0.0,
    },
    Template {
        pid: 6120,
        ppid: 2801,
        uid: 1000,
        user: M,
        state: 'S',
        pri: 20,
        nice: 0,
        nlwp: 182,
        virt_kib: 1_024_000,
        res_kib: 984_000,
        shr_kib: 310_000,
        cpu: 21.4,
        time_cs: 4_812_339,
        starttime: 42_000,
        kthread: false,
        cmdline: "/usr/lib/firefox/firefox",
        comm: "firefox",
        flicker: false,
        read_bps: 260_000.0,
        write_bps: 84_000.0,
    },
    Template {
        pid: 6350,
        ppid: 6120,
        uid: 1000,
        user: M,
        state: 'S',
        pri: 20,
        nice: 0,
        nlwp: 28,
        virt_kib: 2_850_000,
        res_kib: 402_000,
        shr_kib: 150_000,
        cpu: 8.7,
        time_cs: 912_007,
        starttime: 42_300,
        kthread: false,
        cmdline: "/usr/lib/firefox/firefox -contentproc -childID 7 -isForBrowser",
        comm: "Isolated Web Co",
        flicker: false,
        read_bps: 0.0,
        write_bps: 0.0,
    },
    Template {
        pid: 11805,
        ppid: 1,
        uid: 1000,
        user: M,
        state: 'S',
        pri: 20,
        nice: 0,
        nlwp: 12,
        virt_kib: 1_200_000,
        res_kib: 99_900,
        shr_kib: 60_100,
        cpu: 3.2,
        time_cs: 210_455,
        starttime: 39_000,
        kthread: false,
        cmdline: "/usr/bin/ptyxis --gapplication-service",
        comm: "ptyxis",
        flicker: false,
        read_bps: 0.0,
        write_bps: 0.0,
    },
    Template {
        pid: 2801,
        ppid: 11805,
        uid: 1000,
        user: M,
        state: 'S',
        pri: 20,
        nice: 0,
        nlwp: 1,
        virt_kib: 29_016,
        res_kib: 28_248,
        shr_kib: 12_040,
        cpu: 0.0,
        time_cs: 118,
        starttime: 40_100,
        kthread: false,
        cmdline: "bash",
        comm: "bash",
        flicker: false,
        read_bps: 0.0,
        write_bps: 0.0,
    },
    Template {
        pid: 555555,
        ppid: 2801,
        uid: 1000,
        user: M,
        state: 'R',
        pri: 20,
        nice: 0,
        nlwp: 34,
        virt_kib: 3_020_000,
        res_kib: 1_150_000,
        shr_kib: 88_000,
        cpu: 1830.0,
        time_cs: 24_120,
        starttime: 1_610_000,
        kthread: false,
        cmdline: "cargo build --release",
        comm: "cargo",
        flicker: true,
        read_bps: 0.0,
        write_bps: 0.0,
    },
    Template {
        pid: 555601,
        ppid: 555555,
        uid: 1000,
        user: M,
        state: 'R',
        pri: 20,
        nice: 0,
        nlwp: 17,
        virt_kib: 2_100_000,
        res_kib: 890_000,
        shr_kib: 40_000,
        cpu: 640.0,
        time_cs: 8_030,
        starttime: 1_610_400,
        kthread: false,
        cmdline: "rustc --crate-name gridwatch_app --edition=2024",
        comm: "rustc",
        flicker: true,
        read_bps: 0.0,
        write_bps: 0.0,
    },
    Template {
        pid: 1842,
        ppid: 1,
        uid: 1000,
        user: M,
        state: 'S',
        pri: 20,
        nice: 0,
        nlwp: 9,
        virt_kib: 690_000,
        res_kib: 120_500,
        shr_kib: 74_000,
        cpu: 1.1,
        time_cs: 60_311,
        starttime: 38_500,
        kthread: false,
        cmdline: "/usr/bin/pipewire",
        comm: "pipewire",
        flicker: false,
        read_bps: 0.0,
        write_bps: 0.0,
    },
    Template {
        pid: 1849,
        ppid: 1,
        uid: 1000,
        user: M,
        state: 'S',
        pri: 20,
        nice: 0,
        nlwp: 5,
        virt_kib: 310_000,
        res_kib: 35_400,
        shr_kib: 20_100,
        cpu: 0.6,
        time_cs: 30_020,
        starttime: 38_600,
        kthread: false,
        cmdline: "/usr/bin/wireplumber",
        comm: "wireplumber",
        flicker: false,
        read_bps: 0.0,
        write_bps: 0.0,
    },
    Template {
        pid: 1701,
        ppid: 1,
        uid: 1000,
        user: M,
        state: 'S',
        pri: 20,
        nice: 0,
        nlwp: 21,
        virt_kib: 5_800_000,
        res_kib: 402_000,
        shr_kib: 210_000,
        cpu: 2.4,
        time_cs: 400_910,
        starttime: 38_000,
        kthread: false,
        cmdline: "/usr/bin/gnome-shell",
        comm: "gnome-shell",
        flicker: false,
        read_bps: 0.0,
        write_bps: 0.0,
    },
    Template {
        pid: 1,
        ppid: 0,
        uid: 0,
        user: R,
        state: 'S',
        pri: 20,
        nice: 0,
        nlwp: 1,
        virt_kib: 24_900,
        res_kib: 14_900,
        shr_kib: 9_800,
        cpu: 0.0,
        time_cs: 2_110,
        starttime: 12,
        kthread: false,
        cmdline: "/sbin/init splash",
        comm: "systemd",
        flicker: false,
        read_bps: 0.0,
        write_bps: 0.0,
    },
    Template {
        pid: 981,
        ppid: 1,
        uid: 0,
        user: R,
        state: 'S',
        pri: 20,
        nice: 0,
        nlwp: 3,
        virt_kib: 1_890_000,
        res_kib: 97_600,
        shr_kib: 18_000,
        cpu: 0.9,
        time_cs: 200_050,
        starttime: 900,
        kthread: false,
        cmdline: "/usr/bin/dockerd -H fd://",
        comm: "dockerd",
        flicker: false,
        read_bps: 0.0,
        write_bps: 0.0,
    },
    Template {
        pid: 1204,
        ppid: 1,
        uid: 0,
        user: R,
        state: 'S',
        pri: 20,
        nice: 0,
        nlwp: 8,
        virt_kib: 1_540_000,
        res_kib: 45_000,
        shr_kib: 22_000,
        cpu: 0.2,
        time_cs: 40_000,
        starttime: 950,
        kthread: false,
        cmdline: "/usr/sbin/libvirtd",
        comm: "libvirtd",
        flicker: false,
        read_bps: 0.0,
        write_bps: 0.0,
    },
    Template {
        pid: 733,
        ppid: 1,
        uid: 0,
        user: R,
        state: 'S',
        pri: 20,
        nice: 0,
        nlwp: 1,
        virt_kib: 42_000,
        res_kib: 12_500,
        shr_kib: 8_000,
        cpu: 0.0,
        time_cs: 300,
        starttime: 700,
        kthread: false,
        cmdline: "/usr/lib/systemd/systemd-journald",
        comm: "systemd-journal",
        flicker: false,
        read_bps: 0.0,
        write_bps: 0.0,
    },
    Template {
        pid: 802,
        ppid: 1,
        uid: 0,
        user: R,
        state: 'S',
        pri: 20,
        nice: 0,
        nlwp: 1,
        virt_kib: 18_000,
        res_kib: 890,
        shr_kib: 600,
        cpu: 0.0,
        time_cs: 12,
        starttime: 720,
        kthread: false,
        cmdline: "/usr/sbin/acpid",
        comm: "acpid",
        flicker: false,
        read_bps: 0.0,
        write_bps: 0.0,
    },
    Template {
        pid: 4090,
        ppid: 1,
        uid: 0,
        user: R,
        state: 'S',
        pri: 20,
        nice: 0,
        nlwp: 4,
        virt_kib: 1_010_000,
        res_kib: 180_000,
        shr_kib: 30_000,
        cpu: 0.0,
        time_cs: 15_100,
        starttime: 1_200,
        kthread: false,
        cmdline: "/usr/bin/astral-watch serve --exporter",
        comm: "astral-watch",
        flicker: false,
        read_bps: 0.0,
        write_bps: 0.0,
    },
    Template {
        pid: 1330,
        ppid: 1,
        uid: 0,
        user: R,
        state: 'S',
        pri: 20,
        nice: 0,
        nlwp: 2,
        virt_kib: 2_200_000,
        res_kib: 9_800,
        shr_kib: 7_000,
        cpu: 0.0,
        time_cs: 500,
        starttime: 1_000,
        kthread: false,
        cmdline: "/usr/bin/nvidia-persistenced --verbose",
        comm: "nvidia-persiste",
        flicker: false,
        read_bps: 0.0,
        write_bps: 0.0,
    },
    Template {
        pid: 2,
        ppid: 0,
        uid: 0,
        user: R,
        state: 'S',
        pri: 20,
        nice: 0,
        nlwp: 1,
        virt_kib: 0,
        res_kib: 0,
        shr_kib: 0,
        cpu: 0.0,
        time_cs: 10,
        starttime: 12,
        kthread: true,
        cmdline: "",
        comm: "kthreadd",
        flicker: false,
        read_bps: 0.0,
        write_bps: 0.0,
    },
    Template {
        pid: 17,
        ppid: 2,
        uid: 0,
        user: R,
        state: 'S',
        pri: 20,
        nice: 0,
        nlwp: 1,
        virt_kib: 0,
        res_kib: 0,
        shr_kib: 0,
        cpu: 0.4,
        time_cs: 51_200,
        starttime: 12,
        kthread: true,
        cmdline: "",
        comm: "rcu_preempt",
        flicker: false,
        read_bps: 0.0,
        write_bps: 0.0,
    },
    Template {
        pid: 24,
        ppid: 2,
        uid: 0,
        user: R,
        state: 'S',
        pri: 20,
        nice: 0,
        nlwp: 1,
        virt_kib: 0,
        res_kib: 0,
        shr_kib: 0,
        cpu: 0.1,
        time_cs: 9_100,
        starttime: 12,
        kthread: true,
        cmdline: "",
        comm: "ksoftirqd/0",
        flicker: false,
        read_bps: 0.0,
        write_bps: 0.0,
    },
    Template {
        pid: 3801,
        ppid: 2,
        uid: 0,
        user: R,
        state: 'I',
        pri: 20,
        nice: 0,
        nlwp: 1,
        virt_kib: 0,
        res_kib: 0,
        shr_kib: 0,
        cpu: 0.3,
        time_cs: 4_020,
        starttime: 1_400_000,
        kthread: true,
        cmdline: "",
        comm: "kworker/0:1-events",
        flicker: false,
        read_bps: 0.0,
        write_bps: 0.0,
    },
    Template {
        pid: 3902,
        ppid: 2,
        uid: 0,
        user: R,
        state: 'I',
        pri: 20,
        nice: 0,
        nlwp: 1,
        virt_kib: 0,
        res_kib: 0,
        shr_kib: 0,
        cpu: 0.2,
        time_cs: 2_500,
        starttime: 1_450_000,
        kthread: true,
        cmdline: "",
        comm: "kworker/u64:2-events_unbound",
        flicker: false,
        read_bps: 0.0,
        write_bps: 0.0,
    },
    Template {
        pid: 388,
        ppid: 2,
        uid: 0,
        user: R,
        state: 'S',
        pri: -51,
        nice: 0,
        nlwp: 1,
        virt_kib: 0,
        res_kib: 0,
        shr_kib: 0,
        cpu: 0.0,
        time_cs: 800,
        starttime: 300,
        kthread: true,
        cmdline: "",
        comm: "irq/95-nvidia",
        flicker: false,
        read_bps: 0.0,
        write_bps: 0.0,
    },
    Template {
        pid: 1910,
        ppid: 1,
        uid: 1000,
        user: M,
        state: 'S',
        pri: 20,
        nice: 0,
        nlwp: 6,
        virt_kib: 780_000,
        res_kib: 61_200,
        shr_kib: 44_000,
        cpu: 0.5,
        time_cs: 22_000,
        starttime: 38_900,
        kthread: false,
        cmdline: "/usr/libexec/xdg-desktop-portal",
        comm: "xdg-desktop-por",
        flicker: false,
        read_bps: 0.0,
        write_bps: 0.0,
    },
    Template {
        pid: 2210,
        ppid: 1,
        uid: 1000,
        user: M,
        state: 'S',
        pri: 20,
        nice: 0,
        nlwp: 7,
        virt_kib: 880_000,
        res_kib: 75_800,
        shr_kib: 50_000,
        cpu: 0.3,
        time_cs: 15_000,
        starttime: 39_200,
        kthread: false,
        cmdline: "/usr/bin/gjs /usr/share/gnome-shell/org.gnome.Shell.Notifications",
        comm: "gjs",
        flicker: false,
        read_bps: 0.0,
        write_bps: 0.0,
    },
    Template {
        pid: 2333,
        ppid: 1,
        uid: 1000,
        user: M,
        state: 'S',
        pri: 20,
        nice: 0,
        nlwp: 4,
        virt_kib: 420_000,
        res_kib: 22_100,
        shr_kib: 16_000,
        cpu: 0.0,
        time_cs: 1_200,
        starttime: 39_400,
        kthread: false,
        cmdline: "/usr/libexec/gvfsd",
        comm: "gvfsd",
        flicker: false,
        read_bps: 0.0,
        write_bps: 0.0,
    },
    Template {
        pid: 2456,
        ppid: 1,
        uid: 1000,
        user: M,
        state: 'S',
        pri: 20,
        nice: 0,
        nlwp: 3,
        virt_kib: 330_000,
        res_kib: 8_900,
        shr_kib: 7_100,
        cpu: 0.0,
        time_cs: 400,
        starttime: 39_500,
        kthread: false,
        cmdline: "/usr/libexec/at-spi-bus-launcher",
        comm: "at-spi-bus-laun",
        flicker: false,
        read_bps: 0.0,
        write_bps: 0.0,
    },
    Template {
        pid: 2602,
        ppid: 2801,
        uid: 1000,
        user: M,
        state: 'S',
        pri: 20,
        nice: 5,
        nlwp: 1,
        virt_kib: 15_200,
        res_kib: 4_100,
        shr_kib: 3_200,
        cpu: 0.0,
        time_cs: 30,
        starttime: 40_200,
        kthread: false,
        cmdline: "sleep 3600",
        comm: "sleep",
        flicker: false,
        read_bps: 0.0,
        write_bps: 0.0,
    },
    Template {
        pid: 2777,
        ppid: 2801,
        uid: 1000,
        user: M,
        state: 'T',
        pri: 20,
        nice: 0,
        nlwp: 1,
        virt_kib: 22_000,
        res_kib: 5_500,
        shr_kib: 4_000,
        cpu: 0.0,
        time_cs: 110,
        starttime: 40_300,
        kthread: false,
        cmdline: "vim docs/PLAN.md",
        comm: "vim",
        flicker: false,
        read_bps: 0.0,
        write_bps: 0.0,
    },
    Template {
        pid: 2990,
        ppid: 2801,
        uid: 1000,
        user: M,
        state: 'D',
        pri: 20,
        nice: -5,
        nlwp: 2,
        virt_kib: 140_000,
        res_kib: 33_000,
        shr_kib: 9_000,
        cpu: 12.5,
        time_cs: 3_300,
        starttime: 1_590_000,
        kthread: false,
        cmdline: "rsync -a /home/mattbeam/ /mnt/backup/",
        comm: "rsync",
        flicker: false,
        read_bps: 18_400_000.0,
        write_bps: 17_900_000.0,
    },
    Template {
        pid: 3050,
        ppid: 2801,
        uid: 1000,
        user: M,
        state: 'Z',
        pri: 20,
        nice: 0,
        nlwp: 1,
        virt_kib: 0,
        res_kib: 0,
        shr_kib: 0,
        cpu: 0.0,
        time_cs: 60,
        starttime: 1_595_000,
        kthread: false,
        cmdline: "",
        comm: "sh",
        flicker: false,
        read_bps: 0.0,
        write_bps: 0.0,
    },
    Template {
        pid: 3120,
        ppid: 1,
        uid: 0,
        user: R,
        state: 'S',
        pri: 20,
        nice: 19,
        nlwp: 1,
        virt_kib: 58_000,
        res_kib: 3_100,
        shr_kib: 2_500,
        cpu: 0.1,
        time_cs: 900,
        starttime: 1_100,
        kthread: false,
        cmdline: "/usr/bin/gridwatch run --record fixtures/journals/torch-game.jsonl",
        comm: "gridwatch",
        flicker: false,
        read_bps: 0.0,
        write_bps: 0.0,
    },
];

/// The table at `tick` (1.5 s apart): CPU% jitters around each row's mean,
/// TIME+ accrues from it, the flickering PID exists on alternating 8-tick
/// windows. The wiggle draws from its own stream seeded by `(seed, tick)`, so
/// the meters a synth publishes are the same whether or not a table tier is
/// asking for the table (same seed → same meters, D41).
/// The threads the synth's busiest process runs, as htop's `H` would list
/// them (arc 10b, D60). Kept to the game, and hidden by every default filter
/// (`hide_userland_threads`), so the grid tables are byte-identical with or
/// without them — the `full` tier with `H` on is the only place they show.
/// Named after the shape a game's threads really have, because a row of five
/// identical cmdlines would prove nothing about the feature.
const GAME_THREADS: &[(&str, f32, char)] = &[
    ("RenderThread", 96.4, 'R'),
    ("WorkerThread#0", 41.2, 'R'),
    ("WorkerThread#1", 38.7, 'S'),
    ("AudioMixer", 6.1, 'S'),
    ("gc-thread", 2.3, 'S'),
];

pub fn proc_table(tick: u64, seed: u64) -> ProcTable {
    let mut rng = XorShift::new(seed ^ tick.wrapping_mul(0x9E37_79B9_7F4A_7C15));
    let present = (tick / 8).is_multiple_of(2);
    let rows: Vec<ProcRow> = SET
        .iter()
        .filter(|t| !t.flicker || present)
        .map(|t| {
            let jitter = if t.cpu > 0.0 {
                (rng.jitter() as f32) * t.cpu * 0.15
            } else {
                0.0
            };
            let cpu_pct = (t.cpu + jitter).max(0.0);
            // 1.5 s per tick at `cpu` percent of one core = cpu × 1.5 cs.
            let time_cs = t.time_cs + (tick as f64 * f64::from(t.cpu) * 1.5) as u64;
            ProcRow {
                pid: t.pid,
                ppid: t.ppid,
                tgid: t.pid,
                uid: t.uid,
                user: Arc::from(t.user),
                state: t.state,
                pri: t.pri,
                nice: t.nice,
                nlwp: t.nlwp,
                virt_kib: t.virt_kib,
                res_kib: t.res_kib,
                shr_kib: t.shr_kib,
                cpu_pct,
                // The I/O screen's numbers (arc 8a): the backup and the
                // browser move bytes, the rest do not, and the two rows
                // owned by another user are unreadable — which is what a
                // person sees on a real machine.
                read_bps: t.read_bps,
                write_bps: t.write_bps,
                io_readable: t.uid == 1000,
                mem_pct: (t.res_kib as f64 / MEM_TOTAL_KIB * 100.0) as f32,
                time_cs,
                starttime: t.starttime,
                kthread: t.kthread,
                cmdline: Arc::from(if t.cmdline.is_empty() {
                    t.comm
                } else {
                    t.cmdline
                }),
                comm: Arc::from(t.comm),
            }
        })
        .collect();
    // The game's threads, under their leader: same mm, same user, own
    // identity and own CPU time — what `walk_tasks` reads from `task/`.
    let mut rows = rows;
    if let Some(leader) = SET.iter().find(|t| t.cmdline.contains("/game")) {
        let base = rows.iter().find(|r| r.pid == leader.pid).cloned();
        if let Some(base) = base {
            for (i, (comm, cpu, state)) in GAME_THREADS.iter().enumerate() {
                let jitter = (rng.jitter() as f32) * cpu * 0.15;
                rows.push(ProcRow {
                    pid: leader.pid + 1 + i as i32,
                    // The leader, so the tree nests them under it (the tree
                    // groups by `ppid`).
                    ppid: leader.pid,
                    tgid: leader.pid,
                    state: *state,
                    nlwp: 1,
                    cpu_pct: (cpu + jitter).max(0.0),
                    time_cs: (tick as f64 * f64::from(*cpu) * 1.5) as u64,
                    cmdline: Arc::from(*comm),
                    comm: Arc::from(*comm),
                    read_bps: 0.0,
                    write_bps: 0.0,
                    io_readable: false,
                    ..base.clone()
                });
            }
        }
    }
    ProcTable {
        rows,
        pid_digits: PID_DIGITS,
    }
}
