#!/usr/bin/env bash
# Regenerate everything CI drift-checks (D33 executable specs, brief 2a task 5):
# the README SVG screenshots from `shot` (byte-deterministic: embedded config,
# virtual clock, seeded synth — D41), the metric catalogue (`docs/KEYS.md`)
# and the component manifests (`docs/COMPONENTS.md`).
#   scripts/shots.sh            # regenerate in place
#   scripts/shots.sh --check    # regenerate, then fail if git sees a diff
set -euo pipefail
cd "$(dirname "$0")/.."
GW="${GRIDWATCH_BIN:-}"
if [ -z "$GW" ]; then
  cargo build --release --quiet
  GW=target/release/gridwatch
fi
mkdir -p docs/img
# One Overview per built-in theme (arc 9a): the README's gallery, and the
# fastest way to see that a theme change did not quietly break a role.
for t in modern retrowave mono terminal phosphor-green phosphor-amber matrix; do
  "$GW" shot --format svg --size 250x70 --theme "$t" --page 1 > "docs/img/overview-$t.svg"
done
"$GW" shot --format svg --size 120x40 --theme retrowave --page 1 > docs/img/dense-120x40.svg
# The Audio page, where the visualizer and the now-playing tile live.
"$GW" shot --format svg --size 250x70 --theme retrowave --page 2 > docs/img/audio-retrowave.svg
# The README's plain-text frame, between its markers: it showed four tiles as
# "arrives in a later arc" for three arcs after they shipped, because it was
# pasted in by hand. Generated, it cannot rot.
"$GW" shot --format ansi --size 131x37 --theme retrowave --page 1 |
  sed 's/\x1b\[[0-9;]*m//g' | sed 's/[[:space:]]*$//' > /tmp/gw-readme-shot.$$
python3 - "$PWD/README.md" /tmp/gw-readme-shot.$$ <<'PYEOF'
import sys, pathlib
readme, shot = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
s = readme.read_text()
begin = "<!-- BEGIN shot: regenerated by scripts/shots.sh — do not edit -->"
end = "<!-- END shot -->"
i, j = s.index(begin), s.index(end)
block = "```\n" + shot.read_text().rstrip("\n") + "\n```\n"
readme.write_text(s[: i + len(begin)] + "\n" + block + s[j:])
PYEOF
rm -f /tmp/gw-readme-shot.$$
"$GW" keys > docs/KEYS.md
"$GW" keybindings > docs/KEYBINDINGS.md
"$GW" component list > docs/COMPONENTS.md
if [ "${1:-}" = "--check" ]; then
  # A regenerated file that is new (untracked) is drift too — `git diff` alone misses it.
  if ! git diff --exit-code --stat -- docs/img docs/KEYS.md docs/KEYBINDINGS.md docs/COMPONENTS.md README.md || git status --porcelain --untracked-files=all -- docs/img | grep -q '^??'; then
    echo "docs drift: regenerate with scripts/shots.sh and commit" >&2
    exit 1
  fi
  echo "docs in sync"
fi
