#!/usr/bin/env bash
# Regenerate THIRD_PARTY.md from the dependency graph that actually ships
# (D59 seam 3 · arc 9a).
#
#   scripts/third-party.sh            # regenerate in place
#   scripts/third-party.sh --check    # regenerate, then fail if git sees a diff
#
# The list is `cargo tree` for **the Linux target with every feature on**, and
# normal edges only: a dev-dependency is not in your binary, and a crate that
# only exists for some other platform is not either. That second point matters
# — `cargo deny list` enumerates every target and so reports an LGPL crate
# (`r-efi`, via `getrandom` on UEFI) that never enters a Linux build. Reading
# the graph the way a build reads it is the only way to say something true.
set -euo pipefail
cd "$(dirname "$0")/.."

TARGET="${TARGET:-x86_64-unknown-linux-gnu}"
OUT=THIRD_PARTY.md

deps() {
  cargo tree --locked --all-features --target "$TARGET" -e normal --prefix none \
    --format "{p}|{l}" 2>/dev/null |
    sed 's/ (proc-macro)//' |
    grep -v '^gridwatch' |
    grep -v '^$' |
    sort -u
}

{
  cat <<'HEADER'
# Third-party code

> **Generated by `scripts/third-party.sh` — do not edit.** CI regenerates this
> file and fails on drift.

gridwatch is MIT-licensed (see `LICENSE`). It links the crates below, which
carry their own licences. The list is the dependency graph a **Linux release
build with every feature enabled** actually pulls in — normal edges only, so
nothing here is a build-time or test-only dependency.

Two notes for anyone auditing this:

- `cargo deny list` enumerates *every* target, and so reports an
  LGPL-2.1-or-later crate (`r-efi`, reached through `getrandom` on UEFI
  targets). It is not in a Linux build and is not in this list. `cargo deny
  check licenses` passes against the allow-list in `deny.toml`.
- The dynamic libraries gridwatch may `dlopen` at runtime — NVML
  (`libnvidia-ml.so.1`) — are **not** linked and are not listed here. NVML is
  proprietary and belongs to the driver you installed; gridwatch works without
  it and says so (`gridwatch doctor`).

HEADER
  printf '## Crates (%s)\n\n' "$(deps | wc -l)"
  printf '| crate | version | licence |\n|---|---|---|\n'
  deps | while IFS='|' read -r pkg lic; do
    name="${pkg% *}"
    ver="${pkg##* }"
    printf '| `%s` | %s | %s |\n' "$name" "${ver#v}" "${lic:-(unstated)}"
  done
  printf '\n## Licences in use\n\n'
  # `MIT OR Apache-2.0` and the older `MIT/Apache-2.0` are the same two
  # licences; split on both so the histogram counts licences, not spellings.
  deps | cut -d'|' -f2 | tr ' /' '\n\n' | grep -vE '^(OR|AND|WITH)$' |
    sed 's/[()]//g' | grep -v '^$' | sort | uniq -c | sort -rn |
    while read -r n lic; do
      if [ "$n" = 1 ]; then printf -- '- %s — 1 crate\n' "$lic"
      else printf -- '- %s — %s crates\n' "$lic" "$n"; fi
    done
} > "$OUT"

if [ "${1:-}" = "--check" ]; then
  if ! git diff --exit-code --stat -- "$OUT"; then
    # A drift check that only says "it drifted" makes you reproduce it to find
    # out what; print the head of the diff so a CI log is enough.
    echo "--- what changed (first 60 lines) ---" >&2
    git --no-pager diff -- "$OUT" | head -60 >&2
    echo "THIRD_PARTY.md drift: regenerate with scripts/third-party.sh and commit" >&2
    exit 1
  fi
  echo "third-party list in sync"
fi
